### ISSUE TITLE
Read preprocessing

### ISSUE THREAD

**Issue by mmaitenat** [Kevinzjy/CIRI-long#1]
Hi! I am new to Nanopore sequencing data so excuse me if this question seems too obvious. I wanted to know whether there is any preprocessing, besides barcode and adapter trimming, that needs to be done to the sequencing reads before running CIRI-long on them.
Thanks,

Maitena.

**Comment by Kevinzjy** [comment]
Hi @mmaitenat , there's no need to run other QC software. You could just use ont-guppy to demultiplex libraries and use our modified version of [Porechop ](https://github.com/Kevinzjy/Porechop) to remove the library barcodes and SMARTer adapters before running CIRI-long.

**Comment by mmaitenat** [comment]
Great! Thanks so much!
