### ISSUE TITLE
Error when running without genome reference gtf file

### ISSUE THREAD

**Issue by mmaitenat** [Kevinzjy/CIRI-long#2]
Hi again,

I'm trying to run CIRI-long on my own samples. Before that I tried running it with the demo datasets. The example code runs smoothly; however, when ran without the genome reference gtf file (--anno option), it throws the following error:

Traceback (most recent call last):
  File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/bin/CIRI-long", line 33, in <module>
    sys.exit(load_entry_point('CIRI-long==1.0.3', 'console_scripts', 'CIRI-long')())
  File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/lib/python3.6/site-packages/CIRI_long/main.py", line 284, in main
    args.func(args)
  File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/lib/python3.6/site-packages/CIRI_long/main.py", line 100, in call
    tmp_cnt, short_seq = scan_ccs_reads(ccs_seq, ref_fasta, ss_idx, gtf_idx, intron_idx, is_canonical, out_dir, prefix, threads)
UnboundLocalError: local variable 'intron_idx' referenced before assignment

Does this mean that the --anno argument is not optional and should always be passed to the program?

Thanks,

Maitena.

**Comment by Kevinzjy** [comment]
Hi @mmaitenat , could you try cloning the latest version from https://github.com/bioinfo-biols/CIRI-long and try again? This issue should be fixed in v1.0.3.

**Comment by Kevinzjy** [comment]
> Hi again,
> 
> I'm trying to run CIRI-long on my own samples. Before that I tried running it with the demo datasets. The example code runs smoothly; however, when ran without the genome reference gtf file (--anno option), it throws the following error:
> 
> Traceback (most recent call last): File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/bin/CIRI-long", line 33, in sys.exit(load_entry_point('CIRI-long==1.0.3', 'console_scripts', 'CIRI-long')()) File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/lib/python3.6/site-packages/CIRI_long/main.py", line 284, in main args.func(args) File "/usr/nzx-cluster/apps/ciri-long/python3.6.2/lib/python3.6/site-packages/CIRI_long/main.py", line 100, in call tmp_cnt, short_seq = scan_ccs_reads(ccs_seq, ref_fasta, ss_idx, gtf_idx, intron_idx, is_canonical, out_dir, prefix, threads) UnboundLocalError: local variable 'intron_idx' referenced before assignment
> 
> Does this mean that the --anno argument is not optional and should always be passed to the program?
> 
> Thanks,
> 
> Maitena.

By the way, the CIRI-long repository has been transferred to https://github.com/bioinfo-biols/CIRI-long, you could always post new issues there.

**Comment by mmaitenat** [comment]
Hi,

Sorry for posting the issue here, I did not remember the repository had been transferred...
Regarding the CIRI-long version I'm using, I just tested and it turns out that my running version is CIRI-long v1.0.3:

`$ CIRI-long -v`
`CIRI-long v1.0.3`

Thanks!

**Comment by mmaitenat** [comment]
Sorry, I just realized you made some changes to the code few days ago. I'll ask the admin to reinstall the program and let you know if the problem continues. 

Thanks!

**Comment by mmaitenat** [comment]
Hi again,

The problem is solved with the updated version.

Thanks!

**Comment by Kevinzjy** [comment]
> Hi again,
> 
> The problem is solved with the updated version.
> 
> Thanks!

Glad to hear that!
